export const BlogData = [
  {
    title: "product design",
    image_url: "https://bit.ly/dan-abramov",
    blog_cat: "Product management",
    createdAt: "May 23",
    read_time: "20",
    summary: "5 Tips For A Product Manager To Ensure Great Collaboration",
  },
  {
    title: "product design",
    image_url: "https://bit.ly/dan-abramov",
    blog_cat: "Product management",
    createdAt: "May 23",
    read_time: "20",
    summary: "5 Tips For A Product Manager To Ensure Great Collaboration",
  },
  {
    title: "product design",
    image_url: "https://bit.ly/dan-abramov",
    blog_cat: "Product management",
    createdAt: "May 23",
    read_time: "20",
    summary: "5 Tips For A Product Manager To Ensure Great Collaboration",
  },
  {
    title: "product design",
    image_url: "https://bit.ly/dan-abramov",
    blog_cat: "Product management",
    createdAt: "May 23",
    read_time: "20",
    summary: "5 Tips For A Product Manager To Ensure Great Collaboration",
  },
  {
    title: "product design",
    image_url: "https://bit.ly/dan-abramov",
    blog_cat: "Product management",
    createdAt: "May 23",
    read_time: "20",
    summary: "5 Tips For A Product Manager To Ensure Great Collaboration",
  },
  {
    title: "product design",
    image_url: "https://bit.ly/dan-abramov",
    blog_cat: "Product management",
    createdAt: "May 23",
    read_time: "20",
    summary: "5 Tips For A Product Manager To Ensure Great Collaboration",
  },
  {
    title: "product design",
    image_url: "https://bit.ly/dan-abramov",
    blog_cat: "Product management",
    createdAt: "May 23",
    read_time: "20",
    summary: "5 Tips For A Product Manager To Ensure Great Collaboration",
  },
  {
    title: "product design",
    image_url: "https://bit.ly/dan-abramov",
    blog_cat: "Product management",
    createdAt: "May 23",
    read_time: "20",
    summary: "5 Tips For A Product Manager To Ensure Great Collaboration",
  },
  {
    title: "product design",
    image_url: "https://bit.ly/dan-abramov",
    blog_cat: "Product management",
    createdAt: "May 23",
    read_time: "20",
    summary: "5 Tips For A Product Manager To Ensure Great Collaboration",
  },
  {
    title: "product design",
    image_url: "https://bit.ly/dan-abramov",
    blog_cat: "Product management",
    cretedAt: "May 23",
    read_time: "20",
    summary: "5 Tips For A Product Manager To Ensure Great Collaboration",
  },
];
